// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package types

// Budget defines model for budget.
type Budget struct {
	Category string `json:"category"`
	Id       *int   `json:"id,omitempty"`
	Limit    int    `json:"limit"`
}

// BudgetList defines model for budgetList.
type BudgetList = []Budget

// Merchant defines model for merchant.
type Merchant struct {
	Category *string `json:"category,omitempty"`
}

// MerchantList defines model for merchantList.
type MerchantList = []Merchant

// GetMerchantsParams defines parameters for GetMerchants.
type GetMerchantsParams struct {
	FilterUncategorised *bool `form:"filterUncategorised,omitempty" json:"filterUncategorised,omitempty"`
}

// PostBudgetsIdJSONRequestBody defines body for PostBudgetsId for application/json ContentType.
type PostBudgetsIdJSONRequestBody = Budget

// PostMerchantIdJSONRequestBody defines body for PostMerchantId for application/json ContentType.
type PostMerchantIdJSONRequestBody = Merchant
